---
stages:
  - release
  - deploy

include:
  - project: 'connylegal/mietright_deployments'
    ref: main
    file: '/.gitlab-ci/ml.yaml'
  - project: 'connylegal/mietright_deployments'
    ref: main
    file: '/.gitlab-ci/deploy.yaml'

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - /opt/gitlab/cache/image-cache

dockerfile:
  extends: .ml-dockerfile
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG'
  stage: release

build-container:
  extends: .ml-build-container
  needs:
    - dockerfile
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG'
  stage: release

tag image:
  needs:
    - build-container
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG'
  tags:
    - kubernetes
  stage: release
  image:
    name: $OCI_REPO/conny-tools/crane-conny:latest
  script:
    - crane cp $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:$CI_COMMIT_REF_SLUG

deploy-staging:
  extends: .deploy-staging
  variables:
    JOB: deploy-labeling
  needs:
    - tag image

deploy-production:
  extends: .deploy-production
  variables:
    JOB: deploy-labeling
  needs:
    - tag image
