apiVersion: v1
kind: Service
metadata:
  name: labeling
  labels:
    app.kubernetes.io/name: labeling
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    name: http
  selector:
    app.kubernetes.io/name: labeling
