apiVersion: apps/v1
kind: Deployment
metadata:
  name: labeling
  labels:
    app.kubernetes.io/name: labeling
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: labeling
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
      labels:
        app.kubernetes.io/name: labeling

    spec:
      containers:
      - image: img.conny.dev/conny/ml/labeling
        name: model
        command:
          - /miniconda/envs/custom_env/bin/meowlflow
        args:
          - serve
          - --port=8080
          - --schema-path=/opt/meowlflow/schema.py
        ports:
        - containerPort: 8080
          name: http
