apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: labeling
  labels:
    app.kubernetes.io/name: labeling
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: labeling
